Repository kakao-tech-campus-2nd-step3/Team13_FE, pull requests merged in 2024-11, with the labels that each got.

#57 #35 관리자 API 요청 로직 수정
  src/api/hooks/admin/careWorker/careWorkerApi.ts
  src/api/hooks/admin/careWorker/types.ts
  src/api/hooks/admin/guardian/guardianApi.ts
  src/api/hooks/admin/guardian/types.ts
  src/api/hooks/admin/institution/institutionApi.ts
  src/api/hooks/admin/institution/types.ts
  src/api/hooks/admin/recipient/recipientApi.ts
  src/pages/admin/CareWorkerPage.tsx
  src/pages/admin/GuardianPage.tsx
  src/pages/admin/InstitutionPage.tsx
  src/pages/admin/RecipientPage.tsx
Labels: bug, feature

#59 #35 관리자 API 요청 로직 수정
  src/api/hooks/admin/careWorker/careWorkerApi.ts
  src/api/hooks/admin/guardian/guardianApi.ts
  src/api/hooks/admin/institution/institutionApi.ts
  src/api/hooks/admin/institution/types.ts
  src/api/hooks/admin/institution/useUpdateInstitution.ts
  src/api/hooks/admin/recipient/recipientApi.ts
  src/components/common/Table/Table.tsx
  src/pages/admin/CareWorkerPage.tsx
  src/pages/admin/GuardianPage.tsx
  src/pages/admin/InstitutionPage.tsx
  src/pages/admin/RecipientPage.tsx
Labels: bug, feature

#63 #60 요양원, 관리자 로그인 버튼 추가
  src/pages/AudioRecord/AudioRecord.tsx
  src/pages/Home/Home.tsx
  src/routes/path.ts
Labels: design

#64 #35 엑셀 다운로드 및 업로드 모달창 구현
  package-lock.json
  package.json
  src/api/hooks/admin/careWorker/careWorkerApi.ts
  src/api/hooks/admin/guardian/guardianApi.ts
  src/api/hooks/admin/recipient/recipientApi.ts
  src/api/hooks/common/useExcelDownload.ts
  src/api/hooks/common/useExcelUpload.ts
  src/components/common/Modal/Modal.tsx
  src/components/common/Table/Table.tsx
  src/pages/admin/CareWorkerPage.tsx
  src/pages/admin/GuardianPage.tsx
  src/pages/admin/RecipientPage.tsx
Labels: feature, design

#65 #46 요양보호사, 보호자 마이페이지 구현
  package-lock.json
  package.json
  src/api/hooks/common/useLogout.ts
  src/api/hooks/user/my/types.ts
  src/api/hooks/user/my/useUserInfo.ts
  src/api/hooks/user/my/userInfoApi.ts
  src/pages/MyPage/MyPage.styles.ts
  src/pages/MyPage/MyPage.tsx
  src/routes/routes.tsx
Labels: feature, design

#38 #37 카메라 화면 퍼블리싱
  src/assets/icons/download_picture.svg
  src/assets/icons/play.svg
  src/assets/icons/stop.svg
  src/assets/icons/switch.svg
  src/assets/icons/take_picture.svg
  src/pages/AudioRecord/AudioRecord.tsx
  src/pages/Camera/Camera.tsx
Labels: design

#69 #merge week11 -> develop
  src/api/hooks/user/recipient/useGetRecipient.ts
  src/assets/icons/download_picture.svg
  src/assets/icons/play.svg
  src/assets/icons/stop.svg
  src/assets/icons/switch.svg
  src/assets/icons/take_picture.svg
  src/pages/AudioRecord/AudioRecord.tsx
  src/pages/Camera/Camera.tsx
Labels: merge

#72 refactor: 웹 화면 크기 고정
  src/components/common/Back/Back.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Table/Table.styles.ts
  src/components/common/Text/TextFactory.tsx
  src/components/features/MultipleChoice/WriteBox.tsx
  src/pages/Calendar/Calendar.tsx
  src/pages/CareLog/ChoiceLog/Body/BodyChoiceLog.tsx
  src/pages/CareLog/ChoiceLog/Cognitive/CognitiveChoiceLog.tsx
  src/pages/Chart/Chart.tsx
  src/pages/Choice/Body/BodyChoice.tsx
  src/pages/Home/Home.tsx
  src/pages/Landing/components/HeroSection.tsx
  src/pages/Login/Login.tsx
  src/pages/MyPage/MyPage.styles.ts
  src/pages/Recipients/Recipients.tsx
  src/pages/Share/Share.tsx
  src/routes/routes.tsx
Labels: feature, design

#77 feat: 음성인식 구현 및 api 연동
  src/assets/icons/mic_record.svg
  src/assets/images/mic_background.svg
  src/assets/images/mic_record.gif
  src/components/features/SpeechToText/hooks/useSpeechToText.ts
  src/pages/AudioRecord/AudioRecord.tsx
  src/pages/AudioRecord/Check/Check.tsx
  src/pages/Chart/Chart.tsx
  src/pages/Choice/Body/BodyChoice.tsx
  src/pages/Choice/Cognitive/CognitiveChoice.tsx
  src/pages/Choice/Nursing/NursingChoice.tsx
  src/pages/Choice/Recovery/RecoveryChoice.tsx
  src/pages/SpeechToText/SpeechToText.tsx
  src/routes/path.ts
  src/routes/routes.tsx
Labels: feature, design

#79 #74 OCR API 연결
  public/OCR_template.xlsx
  src/api/hooks/user/OCR/usePerformOCR.ts
  src/api/hooks/user/OCR/usePresignedUrl.ts
  src/api/hooks/user/OCR/useSaveImageUrl.ts
  src/pages/OCR/OCR.tsx
  src/pages/OCR/OCRTable/OCRTable.styles.ts
  src/pages/OCR/OCRTable/OCRTable.tsx
  src/utils/dataParser.ts
  src/utils/dataTransformer.ts
Labels: feature

#80 refactor: 디자인 및 시각 수정
  src/pages/CareLog/CareLog.tsx
  src/pages/Recipients/Recipients.tsx
  src/pages/Recipients/RecipientsList.tsx
Labels: refactor, design

#85 feat: 일지 삭제 기능 구현 및 api 연동
  src/api/hooks/user/chart/chartApi.ts
  src/api/hooks/user/chart/useDeleteChart.ts
  src/components/features/CareLog/CareLog.tsx
  src/components/features/DetailLog/DetailLog.tsx
  src/components/features/MultipleChoice/CheckBox.tsx
  src/components/features/MultipleChoice/TimesBox.tsx
  src/pages/Calendar/Calendar.tsx
  src/pages/Camera/Camera.tsx
  src/pages/CareLog/CareLog.tsx
  src/pages/CareLog/ChoiceLog/Body/BodyChoiceLog.tsx
  src/pages/Chart/Chart.tsx
Labels: feature, design

#89 Feature/#74
  src/pages/OCR/OCR.styles.ts
  src/pages/OCR/OCR.tsx
  src/pages/OCR/OCRTable/OCRTable.styles.ts
  src/pages/OCR/OCRTable/OCRTable.tsx
Labels: design

#97 #etc README.md 수정
  README.md
  public/sample.png
  src/api/hooks/admin/careWorker/careWorkerApi.ts
  src/api/hooks/user/chart/chartApi.ts
  src/api/hooks/user/chart/usePostChart.ts
  src/components/common/Table/Table.tsx
  src/components/common/Text/Text.tsx
  src/components/features/MultipleChoice/MultipleBox.tsx
  src/components/molecules/IntroText.tsx
  src/pages/AudioRecord/Check/Check.tsx
  src/pages/Calendar/Calendar.tsx
  src/pages/CareLog/CareLog.tsx
  src/pages/CareLog/ChoiceLog/Body/BodyChoiceLog.tsx
  src/pages/CareLog/ChoiceLog/Cognitive/CognitiveChoiceLog.tsx
  src/pages/CareLog/ChoiceLog/Nursing/NursingChoiceLog.tsx
  src/pages/CareLog/ChoiceLog/Recovery/RecoveryChoiceLog.tsx
  src/pages/CareLog/SignificantLog/SignificantLog.tsx
  src/pages/Chart/Chart.tsx
  src/pages/Landing/components/Footer.tsx
  src/pages/Landing/components/IntroductionSection.tsx
  src/pages/Landing/templates/Page.tsx
  src/pages/Login/Login.tsx
  src/pages/MyPage/MyPage.styles.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/OCR/OCR.tsx
  src/pages/OCR/OCRLoading/OCRLoading.tsx
  src/pages/Recipients/RecipientsList.tsx
  src/pages/Select/Select.tsx
  src/provider/Auth/authApi.tsx
  src/utils/index.ts
Labels: docs
