Repository kakao-tech-campus-2nd-step3/Team13_FE, pull requests merged in 2024-10, with the labels that each got.

#10 #6 촬영, 음성녹음 기능 구현 및 일지 조회 화면 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/components/.gitkeep
  src/components/common/.gitkeep
  src/components/features/CareLog/index.styles.ts
  src/components/features/CareLog/index.tsx
  src/pages/.gitkeep
  src/pages/AudioRecord/index.tsx
  src/pages/Camera/index.tsx
  src/pages/CareLog/index.tsx
  src/pages/Home/index.tsx
  src/routes/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/breakpoints/index.ts
  src/styles/colors/index.ts
Labels: bug, feature, design

#9 #8 화면 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/icons/back_arrow.svg
  src/assets/icons/check_icon.svg
  src/assets/icons/search_icon.svg
  src/assets/images/sample.png
  src/components/common/Back/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Image/index.tsx
  src/components/common/InputField/index.tsx
  src/components/common/Steps/index.tsx
  src/components/common/Text/TextFactory.tsx
  src/components/common/Text/index.tsx
  src/components/common/TextArea/index.tsx
  src/components/features/Layout/index.tsx
  src/pages/Chart/DIY/index.tsx
  src/pages/Login/index.tsx
  src/pages/Recipients/RecipientsList.tsx
  src/pages/Recipients/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/colors/index.ts
  src/types/props.d.ts
  src/types/styles.d.ts
  tsconfig.app.json
  tsconfig.json
Labels: design

#13 #12 OCR, Speech to Text 구현
  package-lock.json
  package.json
  src/components/features/SpeechToText/hooks/useSpeechToText.ts
  src/main.tsx
  src/pages/OCR/index.tsx
  src/pages/SpeechToText/index.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: feature

#16 #merge 5주차 작업 내용 develop으로 merge
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/api/hooks/.gitkeep
  src/api/instance/.gitkeep
  src/assets/fonts/.gitkeep
  src/assets/icons/back_arrow.svg
  src/assets/icons/check_icon.svg
  src/assets/icons/search_icon.svg
  src/assets/images/.gitkeep
  src/assets/images/sample.png
  src/assets/react.svg
  src/components/common/.gitkeep
  src/components/common/Back/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Image/index.tsx
  src/components/common/InputField/index.tsx
  src/components/common/Steps/index.tsx
  src/components/common/Text/TextFactory.tsx
  src/components/common/Text/index.tsx
  src/components/common/TextArea/index.tsx
  src/components/features/CareLog/index.styles.ts
  src/components/features/CareLog/index.tsx
  src/components/features/Layout/index.tsx
  src/components/features/SpeechToText/hooks/useSpeechToText.ts
  src/hooks/.gitkeep
  src/main.tsx
  src/pages/AudioRecord/index.tsx
  src/pages/Camera/index.tsx
  src/pages/CareLog/index.tsx
  src/pages/Chart/DIY/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/OCR/index.tsx
  src/pages/Recipients/RecipientsList.tsx
  src/pages/Recipients/index.tsx
  src/pages/SpeechToText/index.tsx
  src/provider/Auth/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/breakpoints/index.ts
  src/styles/colors/index.ts
  src/styles/reset.css
  src/types/props.d.ts
  src/types/styles.d.ts
  src/utils/.gitkeep
  tsconfig.app.json
  tsconfig.json
Labels: merge

#17 #review 5주차 리뷰 요청
  .github/pull_request_template.md
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/api/hooks/.gitkeep
  src/api/instance/.gitkeep
  src/assets/fonts/.gitkeep
  src/assets/icons/back_arrow.svg
  src/assets/icons/check_icon.svg
  src/assets/icons/search_icon.svg
  src/assets/images/.gitkeep
  src/assets/images/sample.png
  src/assets/react.svg
  src/components/common/.gitkeep
  src/components/common/Back/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Image/index.tsx
  src/components/common/InputField/index.tsx
  src/components/common/Steps/index.tsx
  src/components/common/Text/TextFactory.tsx
  src/components/common/Text/index.tsx
  src/components/common/TextArea/index.tsx
  src/components/features/CareLog/index.styles.ts
  src/components/features/CareLog/index.tsx
  src/components/features/Layout/index.tsx
  src/components/features/SpeechToText/hooks/useSpeechToText.ts
  src/hooks/.gitkeep
  src/main.tsx
  src/pages/AudioRecord/index.tsx
  src/pages/Camera/index.tsx
  src/pages/CareLog/index.tsx
  src/pages/Chart/DIY/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/OCR/index.tsx
  src/pages/Recipients/RecipientsList.tsx
  src/pages/Recipients/index.tsx
  src/pages/SpeechToText/index.tsx
  src/provider/Auth/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/styles/breakpoints/index.ts
  src/styles/colors/index.ts
  src/styles/reset.css
  src/types/props.d.ts
  src/types/styles.d.ts
  src/utils/.gitkeep
  tsconfig.app.json
  tsconfig.json
Labels: review

#20 #19 네이버 CLOVA OCR API 연동
  package-lock.json
  package.json
  src/pages/OCR/index.tsx
  src/services/ocrService.ts
  tsconfig.json
  vite.config.ts
Labels: feature

#21 #merge 6주차 작업 내용 develop으로 merge
  package-lock.json
  package.json
  src/pages/OCR/index.tsx
  src/services/ocrService.ts
  tsconfig.json
  vite.config.ts
Labels: merge

#22 #review 6주차 리뷰 요청
  package-lock.json
  package.json
  src/pages/OCR/index.tsx
  src/services/ocrService.ts
  tsconfig.json
  vite.config.ts
Labels: review

#23 #merge develop -> Master
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.tsx
  src/api/hooks/.gitkeep
  src/api/instance/.gitkeep
  src/assets/fonts/.gitkeep
  src/assets/icons/back_arrow.svg
  src/assets/icons/check_icon.svg
  src/assets/icons/search_icon.svg
  src/assets/images/.gitkeep
  src/assets/images/sample.png
  src/assets/react.svg
  src/components/common/.gitkeep
  src/components/common/Back/index.tsx
  src/components/common/Button/index.tsx
  src/components/common/Image/index.tsx
  src/components/common/InputField/index.tsx
  src/components/common/Steps/index.tsx
  src/components/common/Text/TextFactory.tsx
  src/components/common/Text/index.tsx
  src/components/common/TextArea/index.tsx
  src/components/features/CareLog/index.styles.ts
  src/components/features/CareLog/index.tsx
  src/components/features/Layout/index.tsx
  src/components/features/SpeechToText/hooks/useSpeechToText.ts
  src/hooks/.gitkeep
  src/main.tsx
  src/pages/AudioRecord/index.tsx
  src/pages/Camera/index.tsx
  src/pages/CareLog/index.tsx
  src/pages/Chart/DIY/index.tsx
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/OCR/index.tsx
  src/pages/Recipients/RecipientsList.tsx
  src/pages/Recipients/index.tsx
  src/pages/SpeechToText/index.tsx
  src/provider/Auth/.gitkeep
  src/routes/index.tsx
  src/routes/path.ts
  src/services/ocrService.ts
  src/styles/breakpoints/index.ts
  src/styles/colors/index.ts
  src/styles/reset.css
  src/types/props.d.ts
  src/types/styles.d.ts
  src/utils/.gitkeep
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: merge

#24 #setting vercel.json 추가
  vercel.json
Labels: setting

#26 week8 -> develop
  src/assets/icons/camera.svg
  src/assets/icons/gallery.svg
  src/assets/icons/next_arrow.svg
  src/assets/icons/pencil.svg
  src/assets/icons/recording.svg
  src/components/common/Date/Date.styles.ts
  src/components/common/Date/Date.tsx
  src/components/common/TextArea/index.tsx
  src/components/features/DetailLog/index.tsx
  src/pages/CareLog/DetailLog/index.tsx
  src/pages/Chart/Chart.tsx
  src/pages/OCR/OCRCheck/index.tsx
  src/pages/Share/Share.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: merge

#27 #review 8주차 리뷰 요청
  src/assets/icons/camera.svg
  src/assets/icons/gallery.svg
  src/assets/icons/next_arrow.svg
  src/assets/icons/pencil.svg
  src/assets/icons/recording.svg
  src/components/common/Date/Date.styles.ts
  src/components/common/Date/Date.tsx
  src/components/common/TextArea/index.tsx
  src/components/features/DetailLog/index.tsx
  src/pages/CareLog/DetailLog/index.tsx
  src/pages/Chart/Chart.tsx
  src/pages/OCR/OCRCheck/index.tsx
  src/pages/Share/Share.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: review

#18 #15 상세 일지 화면, OCR 수정 화면 퍼블리싱
  src/assets/icons/camera.svg
  src/assets/icons/gallery.svg
  src/assets/icons/next_arrow.svg
  src/assets/icons/pencil.svg
  src/assets/icons/recording.svg
  src/components/common/Date/Date.styles.ts
  src/components/common/Date/Date.tsx
  src/components/common/TextArea/index.tsx
  src/components/features/DetailLog/index.tsx
  src/pages/CareLog/DetailLog/index.tsx
  src/pages/Chart/Chart.tsx
  src/pages/OCR/OCRCheck/index.tsx
  src/pages/Share/Share.tsx
  src/routes/index.tsx
  src/routes/path.ts
Labels: design
